env:
  DOCKER_COMPOSE_VERSION: 1.11.2

sudo: required

languge: node

services:
  - docker

install:
  - docker build -t gabriel .
  - docker build -t test -f Dockerfile.test .

script:
  - docker run test
