version: "3"
services:
  app:
    build:
      context: .
    environment:
      - NODE_ENV=production
  test:
    build:
      context: .
    depends_on:
      - "app"
    command: ["npm", "test"]
    environment:
      - GAVRIEL_URL=http://app:3030
